# Relatório de Escolas Ativas - SEDUC MT
- GER | 09 - Relação de Escolas Ativas

- GED | 35C - Relação de Turmas Regulares Ano Atual
- http://bi.seduc.mt.gov.br/Default.aspx

In [10]:
import pandas as pd
# Exibir todas as colunas sem truncamento
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [24]:
df = pd.read_csv("escolas_relatorio.csv", sep=";") # Se o arquivo usar ponto e vírgula:

# exibir quantidade de linhas e colunas - df.shpae[0] pega o número de linhas e df.shpae[1] o de colunas.
print(f"Linhas: {df.shape[0]} | Colunas: {df.shape[1]}\n")
print(df.columns.tolist(), "\n") # exibe o nome das colunas em uma lista comum

# Filtrar por AnoLetivo = 2026 E SituacaoEducacenso = 'ATIVA'
df = df[(df["AnoLetivo"] == 2026) & (df["SituacaoEducacenso"] == "ATIVA")]
print(f"Linhas: {df.shape[0]} | Colunas: {df.shape[1]}\n")
display(df)
#df.head(3)

Linhas: 705 | Colunas: 59

['Polo', 'Municipio', 'Lotacao', 'SerieLotacao', 'CodINEP', 'AnoLetivo', 'CodTpLot', 'TpLotacao', 'Porte', 'TipoPredio', 'Endereco', 'Bairro', 'CEP', 'Localizacao', 'Telefone', 'Email', 'Diretor', 'RG_Dir', 'CPF_Dir', 'SexoDir', 'TipoServidorDir', 'VinculoDir', 'PartcEleicaoDir', 'EscolaridadeDir', 'EnderecoDir', 'BairroDir', 'MunicipioDir', 'TelefoneDir', 'CelularDir', 'EmailDir', 'AtrInicialDir', 'AtrFinalDir', 'PresidenteCDCE', 'EmailPresCDCE', 'Secretario', 'TipoVinculoSec', 'EnderecoSec', 'Nº', 'BairroSec', 'MunicipioSec', 'TelefoneSec', 'CelularSec', 'EmailSec', 'AtrInicialSec', 'AtrFinalSec', 'CoordenadorPedagogico', 'VinculoCoordPed', 'CNPJ', 'DecretoCriação', 'DecretoDenominação', 'DataDecretoDenominação', 'Latitude', 'Longitude', 'SituacaoEducacenso', 'Opção de Atendimento - PAS', 'PossuiMatricula', 'QtdeMatriculasAtivas', 'NomeCDCE', 'Unnamed: 58']

Linhas: 634 | Colunas: 59

,Polo,Municipio,Lotacao,SerieLotacao,CodINEP,AnoLetivo,CodTpLot,TpLotacao,Porte,TipoPredio,Endereco,Bairro,CEP,Localizacao,Telefone,Email,Diretor,RG_Dir,CPF_Dir,SexoDir,TipoServidorDir,VinculoDir,PartcEleicaoDir,EscolaridadeDir,EnderecoDir,BairroDir,MunicipioDir,TelefoneDir,CelularDir,EmailDir,AtrInicialDir,AtrFinalDir,PresidenteCDCE,EmailPresCDCE,Secretario,TipoVinculoSec,EnderecoSec,Nº,BairroSec,MunicipioSec,TelefoneSec,CelularSec,EmailSec,AtrInicialSec,AtrFinalSec,CoordenadorPedagogico,VinculoCoordPed,CNPJ,DecretoCriação,DecretoDenominação,DataDecretoDenominação,Latitude,Longitude,SituacaoEducacenso,Opção de Atendimento - PAS,PossuiMatricula,QtdeMatriculasAtivas,NomeCDCE,Unnamed: 58
1,DRE ALTA FLORESTA,ALTA FLORESTA ...,EE PROFª MARINES FÁTIMA DE SÁ TEIXEIRA,15474,51003830.0,2026,1,ESCOLA,GRANDE,PRÓPRIO,AVENIDA LUDOVICO DA RIVA NETO,CENTRO,78.580-000,Urbana,66 -35213677,escola.15474@edu.mt.gov.br,MARCIO HRYCYK,08311846,5.365642e+10,M,PROFESSOR,EFETIVO,NÃO PARTICIPOU,MESTRADO,AVENIDA AMAZONAS,CIDADE ALTA,ALTA FLORESTA ...,66 -35213810,66 -992112849,marciohrycyk@yahoo.com.br,19/1/2026 0:00:00,18/12/2026 0:00:00,MARCIO HRYCYK,marciohrycyk@yahoo.com.br,MARCIA ANDRADE CAMILO,EFETIVO,OUTROS RUA B 5,1702,CENTRO,ALTA FLORESTA ...,66 -35211284,66 -992142606,marcia_camilo844@hotmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,ELIZANGELA ALVES SOUSA MARQUES,EFETIVO,01350294000144,2.147,5.118,7/5/1987 0:00:00,-9.88540403,-56.08664695,ATIVA,Regular,SIM,886,Conselho Deliberativo - EE PROFª MARINES FÁTIM...,NaN
2,DRE ALTA FLORESTA,ALTA FLORESTA ...,EE RUI BARBOSA,15482,51003562.0,2026,1,ESCOLA,GRANDE,PRÓPRIO,AVENIDA MINAS GERAIS,CIDADE ALTA,78.580-000,Urbana,66 -35211497,escola.15482@edu.mt.gov.br,JUCINEI DA SILVA ARRUDA,21389047,2.345282e+09,M,PROFESSOR,EFETIVO,NÃO PARTICIPOU,MESTRADO,RUA D5,SETOR D,ALTA FLORESTA ...,66 -35211497,65 -996768624,jucineiarruda@hotmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,JUCINEI DA SILVA ARRUDA,jucineiarruda@hotmail.com,MARIO SERGIO PEREIRA,EFETIVO,RUA C1,46,SETOR C,ALTA FLORESTA ...,NaN,66 -992046894,mario.sergio.af@hotmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,MEIRE MAZUREKI,EFETIVO,01347952000149,174,NaN,1/1/1753 0:00:00,-9.85385602,-56.07179241,ATIVA,Regular,SIM,585,Conselho Deliberativo - EE RUI BARBOSA,NaN
3,DRE ALTA FLORESTA,ALTA FLORESTA ...,EE MUNDO NOVO,15504,51003554.0,2026,20,ESCOLA CAMPO,MÉDIA,PRÓPRIO,3ª VICINAL LESTE COMUNIDADE MUNDO NOVO,ZONA RURAL,78.580-000,Rural,66 -984330626,escola.15504@edu.mt.gov.br,RENATO JOSE FERREIRA,12932906,9.300236e+10,M,PROFESSOR,EFETIVO,NÃO PARTICIPOU,MESTRADO,OUTROS RUA VITORIA,CIDADE ALTA,ALTA FLORESTA ...,65 -996062136,65 -996062136,renatoferreir_572@hotmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,RENATO JOSE FERREIRA,renatoferreir_572@hotmail.com,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DARLENE CRISTINA GONCALVES DOS SANTOS DELARINCY,EFETIVO,01347959000160,43,NaN,1/1/1753 0:00:00,-9.851379,-55.938692,ATIVA,Regular,SIM,186,CONSELHO DELIBERATIVO - EE MUNDO NOVO,NaN
4,DRE ALTA FLORESTA,ALTA FLORESTA ...,EE DOM BOSCO,15547,51064090.0,2026,1,ESCOLA,MÉDIA,PRÓPRIO,RUA JOÃO DE BARRO,JARDIM DAS ARARAS,78.580-000,Urbana,66 -35212399,escola.15547@edu.mt.gov.br,VAGNA MARTINS FERNANDES LINO,11239573,9.433342e+10,F,PROFESSOR,EFETIVO,NÃO PARTICIPOU,ESPECIALIZAÇÃO,RUA PAPA JOAO XIII,SETOR B,ALTA FLORESTA ...,66 -35212143,66 -992362681,vagnamartins@yahoo.com.br,19/1/2026 0:00:00,18/12/2026 0:00:00,VAGNA MARTINS FERNANDES LINO,vagnamartins@yahoo.com.br,JESSICA ALVES SILVA DUARTE,EFETIVO,RUA SAO GABRIEL,111,BOA NOVA III,ALTA FLORESTA ...,66 -35216981,66 -992188562,jesskduarte22@hotmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,DJALMA GONCALVES RAMIRES,EFETIVO,01347956000127,1.780,NaN,1/1/1753 0:00:00,-9.89577602,-56.07464067,ATIVA,Regular,SIM,214,CONSELHO DELIBERATIVO - EE DOM BOSCO,NaN
5,DRE ALTA FLORESTA,ALTA FLORESTA ...,EECM CECÍLIA MEIRELES,15601,51090317.0,2026,1,ESCOLA,MÉDIA,PRÓPRIO,Av. Amazonas,Cidade Bela,78.580-000,Urbana,66 -992126330,escola.15601@edu.mt.gov.br,EVELIN TAISA BORBA DOS SANTOS BARROS,18137300,3.647254e+09,F,TÉCNICO ADMINISTRATIVO EDUCACIONAL,EFETIVO,NÃO PARTICIPOU,MESTRADO,OUTROS RUA ARAGUAIA,BOA VISTA,ALTA FLORESTA ...,66 -992314439,66 -992314439,evelin.barros@edu.mt.gov.br,19/1/2026 0:00:00,18/12/2026 0:00:00,EVELIN TAISA BORBA DOS SANTOS BARROS,evelin.barros@edu.mt.gov.br,MARCIA AGUIAR DA SILVA,EFETIVO,RUA BELO HORIZONTE,141,CIDADE ALTA,ALTA FLORESTA ...,66 -35212947,66 -992250167,marciaaguiardasilva@yahoo.com.br,2/3/2026 0:00:00,18/12/2026 0:00:00,VANDA APARECIDA GODOI,EFETIVO,01454413000109,509,1889,5/2/2026 0:00:00,-9.8495868,-56.07942806,ATIVA,Regular,SIM,654,CONSELHO DELIBERATIVO - EECM CECÍLIA MEIRELES,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,DRE TANGARÁ DA SERRA,TANGARA DA SERRA ...,EE PROF. JOÃO BATISTA,16020,51028492.0,2026,1,ESCOLA,GRANDE,PRÓPRIO,AVENIDA ISMAEL JOSÉ DO NASCIMENTO,CENTRO - JARDIM EUROPA -SETOR NORTE,78.300-152,Urbana,65 -33291021,escola.16020@edu.mt.gov.br,EDMA NEUSA DE MORAES RIBEIRO,3974262,6.052942e+08,F,PROFESSOR,EFETIVO,NÃO PARTICIPOU,ESPECIALIZAÇÃO,RUA 50,NOVO TARUMA,TANGARA DA SERRA ...,65 -33271101,65 -996949214,edma0712@outlook.com,19/1/2026 0:00:00,18/12/2026 0:00:00,EDMA NEUSA DE MORAES RIBEIRO,edma0712@outlook.com,ROSANGELA MARQUES DE MORAES,EFETIVO,RUA 46,892,JARDIM PARAISO,TANGARA DA SERRA ...,65 -33265445,65 -999854256,rosangela.tga@hotmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,DJEOVANI ROOS,EFETIVO,02010870000177,992,NaN,1/1/1753 0:00:00,-14.61158273,-57.48355534,ATIVA,Regular,SIM,851,Conselho Deliberativo - EE PROF. JOÃO BATISTA,NaN
700,DRE TANGARÁ DA SERRA,TANGARA DA SERRA ...,EE DR. HELCIO DE SOUZA,23841,51027950.0,2026,1,ESCOLA,MÉDIA,PRÓPRIO,RUA CINCO,JARDIM NAZARÉ,78.307-112,Urbana,65 -33254196,escola.23841@edu.mt.gov.br,MARIA NELI BARRETO,14808978,9.784656e+10,F,PROFESSOR,EFETIVO,NÃO PARTICIPOU,MESTRADO,RUA 40,JARDIM SANTA ISABEL,TANGARA DA SERRA ...,65 -33262475,65 -996426495,nelibarretolima@gmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,MARIA NELI BARRETO,nelibarretolima@gmail.com,LIVICE GOMES OLIVEIRA SANTOS,EFETIVO,RUA CARDEAL ESQUINA COM A JABURU,92,ALTO DA BOA VISTA,TANGARA DA SERRA ...,65 -996600107,65 -996600107,livice2016@gmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,MARLI TEODORO DE OLIVEIRA DOS SANTOS,EFETIVO,02506868000193,3.695,NaN,1/1/1753 0:00:00,-14.64218349,-57.48367542,ATIVA,Regular,SIM,428,Conselho Deliberativo - EE DR. HELCIO DE SOUZA,NaN
701,DRE TANGARÁ DA SERRA,TANGARA DA SERRA ...,EE PAULO FREIRE,76198,51090457.0,2026,20,ESCOLA CAMPO,MÉDIA,PRÓPRIO,ÁREA RURAL,ÁREA RURAL DE TANGARÁ DA SERRA,78307899,Rural,65 -999808644,escola.76198@edu.mt.gov.br,MARIO CESAR NEPOMUCENO DOS SANTOS,040669,2.025590e+10,M,PROFESSOR,EFETIVO,PARTICIPOU,ESPECIALIZAÇÃO,RUA 06,JARDIM NAZARÉ,TANGARA DA SERRA ...,66 -999870834,66 -999870834,mario.santos@edu.mt.gov.br,19/1/2026 0:00:00,18/12/2026 0:00:00,MARIO CESAR NEPOMUCENO DOS SANTOS,mario.santos@edu.mt.gov.br,INDONESIA REZENDE,EFETIVO,RUA 6,S/N,JARDIM NAZARE,TANGARA DA SERRA ...,66 -992250902,66 -992250902,indonesia.rezende@edu.mt.gov.br,19/1/2026 0:00:00,18/12/2026 0:00:00,NaN,NaN,05665466000120,5.878,NaN,1/1/1753 0:00:00,-14.95344913,-57.71582499,ATIVA,Regular,SIM,72,CONSELHO DELIBERATIVO - EE PAULO FREIRE,NaN
702,DRE TANGARÁ DA SERRA,TANGARA DA SERRA ...,EEI MALAMALALI,129259,51095076.0,2026,16,ESCOLA INDÍGENA,PEQUENA,PRÓPRIO,ÁREA RURAL,ÁREA RURAL DE TANGARÁ DA SERRA,78307899,Rural,65 -33262612,escola.129259@edu.mt.gov.br,WILLIAN MARS CRISTIANO NAZOKEMAI,22617434,3.438960e+09,M,PROFESSOR CONTRATO TEMPORÁRIO,CONTRATADO,NÃO PARTICIPOU,ENSINO MÉDIO,ALDEIA RIO VERDE,ZONA RURAL,TANGARA DA SERRA ...,NaN,65 -999511592,wnazokemai@gmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,WILLIAN MARS CRISTIANO NAZOKEMAI,wnazokemai@gmail.com,MARCIO SILVA PEREIRA,EFETIVO,OUTROS GRANDE USUARIO AVENIDA BRASIL 104E,0,CENTRO,TANGARA DA SERRA ...,65 -33262612,65 -999573160,marcio-tga@hotmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,NaN,NaN,10017571000192,200,1.365,19/4/2022 0:00:00,-14.38055556,-58.23358056,ATIVA,Regular,SIM,57,CONSELHO DELIBERATIVO - EEI MALAMALALI,NaN
704,DRE TANGARÁ DA SERRA,TANGARA DA SERRA ...,EE MILITAR TIRADENTES 1º TENENTE PM SALOMÃO FE...,213454,51070235.0,2026,1,ESCOLA,MÉDIA,PRÓPRIO,RUA MANOEL DIONÍSIO SOBRINHO,CENTRO,78.300-066,Urbana,65 -996351680,escola.213454@edu.mt.gov.br,NEWTON LUIZ VASCONCELOS DE BRITO JÚNIOR,877755,4.954282e+10,M,PROFESSOR - PERMUTA / REDIMENSIONAMENTO,EFETIVO,NÃO PARTICIPOU,ENSINO SUPERIOR,AREA RURAL COMUNIDADE SAO JOSE,AREA RURAL DE TANGARA DA SERRA,TANGARA DA SERRA ...,NaN,65 -999043858,newtonbritojunior@gmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,NEWTON LUIZ VASCONCELOS DE BRITO JÚNIOR,newtonbritojunior@gmail.com,LEICIMAR MARQUES DE ALMEIDA,EFETIVO,RUA 20B,233-S,JARDIM TANAKA,TANGARA DA SERRA ...,65 -996657989,65 -996657989,leicimar_1@hotmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,RIAMAR RAMIRES DA CRUZ,EFETIVO,41929088000108,816,1.451,16/8/2022 0:00:00,NaN,NaN,ATIVA,Regular,SIM,517,Conselho Deliberativo - EE MILITAR TIRADENTES ...,NaN

In [14]:
#df = df[["Cod_Lotação", "CNPJ"]]
#display(df)
#df.to_excel("lotacao-cnpj.xlsx", sheet_name="lotacao", index=False)

In [15]:
# Buscar CNPJ 07518670000143
cnpj_busca = "07518670000143"

# 1) Busca exata (só funciona se o CNPJ estiver completo no arquivo)
cnpj_limpo = df["CNPJ"].astype(str).str.replace(r"\D", "", regex=True).str.zfill(14)
resultado = df[cnpj_limpo == cnpj_busca]

# 2) Se não achar, busca aproximada (o CSV tem CNPJ em notação científica, ex.: 7,51867E+12)
if resultado.empty:
    cnpj_num = pd.to_numeric(df["CNPJ"].astype(str).str.replace(",", "."), errors="coerce")
    alvo = int(cnpj_busca)
    resultado = df[(cnpj_num - alvo).abs() < 1e8]  # tolerância pela perda de dígitos
    print("Busca aproximada (CNPJ truncado no arquivo):")

display(resultado)

,Polo,Municipio,Lotacao,SerieLotacao,CodINEP,AnoLetivo,CodTpLot,TpLotacao,Porte,TipoPredio,Endereco,Bairro,CEP,Localizacao,Telefone,Email,Diretor,RG_Dir,CPF_Dir,SexoDir,TipoServidorDir,VinculoDir,PartcEleicaoDir,EscolaridadeDir,EnderecoDir,BairroDir,MunicipioDir,TelefoneDir,CelularDir,EmailDir,AtrInicialDir,AtrFinalDir,PresidenteCDCE,EmailPresCDCE,Secretario,TipoVinculoSec,EnderecoSec,Nº,BairroSec,MunicipioSec,TelefoneSec,CelularSec,EmailSec,AtrInicialSec,AtrFinalSec,CoordenadorPedagogico,VinculoCoordPed,CNPJ,DecretoCriação,DecretoDenominação,DataDecretoDenominação,Latitude,Longitude,SituacaoEducacenso,Opção de Atendimento - PAS,PossuiMatricula,QtdeMatriculasAtivas,NomeCDCE,Unnamed: 58
571,DRE RONDONÓPOLIS,RONDONOPOLIS ...,EE PINDORAMA,11002,51051940.0,2026,1,ESCOLA,GRANDE,PRÓPRIO,Rua Augusto de Moraes,Santa Cruz,78.710-790,Urbana,66 -30233810,escola.11002@edu.mt.gov.br,CRISTIANO BARBOZA DA CUNHA,11160489,6.895447e+10,M,PROFESSOR,EFETIVO,PARTICIPOU,ESPECIALIZAÇÃO,RUA ALAMEDA DAS TULIPAS,VILA ESPERANCA,RONDONOPOLIS ...,NaN,66 -996362690,cristiano_26barboza@hotmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,CRISTIANO BARBOZA DA CUNHA,cristiano_26barboza@hotmail.com,JUCIANE MOREIRA JERONIMO DE GODOI,EFETIVO,OUTROS ALAMEDA DAS ROSAS,990,VILA AURORA,RONDONOPOLIS ...,66 -34691062,66 -992447765,jucinelo@hotmail.com,19/1/2026 0:00:00,18/12/2026 0:00:00,JEISON CARLOS DE SOUZA,EFETIVO,07518670000143,825,NaN,1/1/1753 0:00:00,-16.45948,-54.63012,ATIVA,Regular,SIM,325,CONSELHO DELIBERATIVO - EE PINDORAMA,NaN

In [22]:
#df.to_excel("escolas-ativas-2026.xlsx", sheet_name="lotacao", index=False)